### ISSUE TITLE
Can't install on CI4

### ISSUE THREAD

**Issue by hieuhuynh93** [KejawenLab/CI4Pager#1]
Hi,
I'm using CI 4.0.4, I can't install this library. It show the error message:
`  Problem 1
    - Installation request for kejawenlab/ci4pager ^1.0 -> satisfiable by kejawenlab/ci4pager[1.0].
    - kejawenlab/ci4pager 1.0 requires codeigniter4/framework dev-master -> satisfiable by codeigniter4/framework[dev-master] but these conflict with your requirements or minimum-stability.
`

Please help me check it. Thanks.

**Comment by ad3n** [comment]
Hi @hieuhuynh93 i update the CI Version, now you can use this package
